version: '3.4'

services:
  sql.data:
    image: mcr.microsoft.com/mssql/server:2022-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  microservices.playground.serviceone.api:
    image: ${DOCKER_REGISTRY-}microservicesplaygroundserviceoneapi
    build:
      context: .
      dockerfile: src/MicroServices.Playground.ServiceOne.Api/Dockerfile

  microservices.playground.servicetwo.api:
    image: ${DOCKER_REGISTRY-}microservicesplaygroundservicetwoapi
    build:
      context: .
      dockerfile: src/MicroServices.Playground.ServiceTwo.Api/Dockerfile


  microservices.playground.webapp:
    image: ${DOCKER_REGISTRY-}microservicesplaygroundwebapp
    build:
      context: .
      dockerfile: src/MicroServices.Playground.WebApp/Dockerfile

